### PR TITLE
[FIX] #61, #62

### PR DESCRIPTION
**Pull request by Zethson**
## PR checklist
 - [ x ] This comment contains a description of changes (with reason)

Fixes 
https://github.com/nf-core/mhcquant/issues/61

https://github.com/nf-core/mhcquant/issues/62

### CODE REVIEW

**Comment by Leon-Bichmann** [comment]
There seems to be a problem with the empty quotes, I guess thats why travis fails and probably why I removed them in the first place.

Would the tokenize trick work on fixed mods as well?

**Comment by Zethson** [comment]
That's the only thing that I just expected to work and didn't test haha.
I will try.

**Comment by Zethson** [comment]
Works again.

**Comment by Leon-Bichmann** [comment]
ok looking fine, testing it as well once again.

**Comment by Leon-Bichmann** [comment]
ok so it's running but some parameters are not correctly handed over:

./nextflow run MHCquant/ -profile docker,test --fixed_modifications 'Acetyl (K)' 
 --variable_modifications 'Oxidation (M), Carbamidomethyl (C)'

resulted in the following parameters handed to comet ...

```
CometAdapter  -in MM15_Melanom_2_B_1.mzML \
              -out MM15_Melanom_2_B_1.idXML \
              -threads 2 \
              -database test_decoy.fasta \
              -precursor_mass_tolerance 5 \
              -fragment_bin_tolerance 0.02 \
              -fragment_bin_offset 0 \
              -num_hits 1 \
              -digest_mass_range 800:2500 \
              -max_variable_mods_in_peptide 3 \
              -allowed_missed_cleavages 0 \
              -precursor_charge 2:3 \
              -activation_method ALL \
              -use_NL_ions true \
              -variable_modifications 'Oxidation (M)' \
              -fixed_modifications  \
              -enzyme 'unspecific cleavage' \
              -spectrum_batch_size 500
```

**Comment by Zethson** [comment]
Ah I think I know why that could happen.
Could you try again with
--variable_mods "Carbamidomethyl (C)" , "Oxidation (M)"
?

**Comment by Leon-Bichmann** [comment]
> Ah I think I know why that could happen.
> Could you try again with
> --variable_mods "Carbamidomethyl (C)" , "Oxidation (M)"
> ?

My bad it also worked like this now: 
./nextflow run MHCquant/ -profile docker,test --fixed_mods 'Acetyl (K)' --variable_mods 'Carbamidomethyl (C),Oxidation (M)'

**Pull request merged**
