### PR TITLE
Update modules.config

### PR DESCRIPTION
**Pull request by ricardojacomini**
The openms_comet_adapter there are options is missing on OpenMS.

|                  is                            |       should be
| ----------------------------|---------------------------
|  fragment_bin_tolerance      | fragment_mass_tolerance
|  allowed_missed_cleavages | missed_cleavages

## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
    - [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/mhcquant/tree/master/.github/CONTRIBUTING.md)
    - [ ] If necessary, also make a PR on the nf-core/mhcquant _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

### CODE REVIEW

**Comment by marissaDubbelaar** [comment]
Hey @ricardojacomini,
I noticed that you wanted to do a PR, help is always welcome of course 🙌 
However, keep in mind the [nf-core guidelines](https://nf-co.re/developers/release_checklist) and the [contribution docs](https://github.com/nf-core/mhcquant/blob/master/.github/CONTRIBUTING.md).

For the work that you suggested, I already altered it in the dev branch. Since the dev is merged with the master branch, the suggestions of this PR are already part of the new (release)[https://github.com/nf-core/mhcquant/releases/tag/2.1.0] 😉

**Comment by ricardojacomini** [comment]
Hi Marissa,

Thank you for reaching out to me. I really appreciate it.

Sorry, for that. I make a fork and change it on my profile. So, I will do the PR as you told me.

Cheers,

From: Marissa Dubbelaar ***@***.***>
Date: Thursday, December 9, 2021 at 9:12 AM
To: nf-core/mhcquant ***@***.***>
Cc: Ricardo de Souza Jacomini ***@***.***>, Mention ***@***.***>
Subject: Re: [nf-core/mhcquant] Update modules.config (PR #180)

      External Email - Use Caution





Hey @ricardojacomini<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fricardojacomini&data=04%7C01%7Cricardo.jacomini%40jhu.edu%7C08d3e06858cd4c3029ff08d9bb1df0a7%7C9fa4f438b1e6473b803f86f8aedf0dec%7C0%7C0%7C637746559540321245%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=eUPd2oFzLEqrLVTez6ETDi2tBIlGrwbo3NDBxsS93vc%3D&reserved=0>,
I noticed that you wanted to do a PR, help is always welcome of course 🙌
However, keep in mind the nf-core guidelines<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fnf-co.re%2Fdevelopers%2Frelease_checklist&data=04%7C01%7Cricardo.jacomini%40jhu.edu%7C08d3e06858cd4c3029ff08d9bb1df0a7%7C9fa4f438b1e6473b803f86f8aedf0dec%7C0%7C0%7C637746559540321245%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=hbYJgv21qsTFGoNluya5APLL8tfYI9OY1XzVhP%2FWh7k%3D&reserved=0> and the contribution docs<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnf-core%2Fmhcquant%2Fblob%2Fmaster%2F.github%2FCONTRIBUTING.md&data=04%7C01%7Cricardo.jacomini%40jhu.edu%7C08d3e06858cd4c3029ff08d9bb1df0a7%7C9fa4f438b1e6473b803f86f8aedf0dec%7C0%7C0%7C637746559540321245%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=v5jvN53WdO%2B%2FDLJZLV8F%2BO7JYDP74IHLtTiUHNwcZ%2BI%3D&reserved=0>.

For the work that you suggested, I already altered it in the dev branch. Since the dev is merged with the master branch, the suggestions of this PR are already part of the new (release)[https://github.com/nf-core/mhcquant/releases/tag/2.1.0] 😉

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnf-core%2Fmhcquant%2Fpull%2F180%23issuecomment-989889044&data=04%7C01%7Cricardo.jacomini%40jhu.edu%7C08d3e06858cd4c3029ff08d9bb1df0a7%7C9fa4f438b1e6473b803f86f8aedf0dec%7C0%7C0%7C637746559540321245%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=sHgUYMl9%2BGP4UZMjHSU%2FoSjpJ%2F7%2Ff5GehCbLdKHkqRo%3D&reserved=0>, or unsubscribe<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAA6V5IQ3M7OT2BY2VEFWBXDUQC2M5ANCNFSM5JUYQUJQ&data=04%7C01%7Cricardo.jacomini%40jhu.edu%7C08d3e06858cd4c3029ff08d9bb1df0a7%7C9fa4f438b1e6473b803f86f8aedf0dec%7C0%7C0%7C637746559540321245%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=PrcWGh8sNmcM4vdJwy%2Bb14VO20z2YA41Ce5Vch%2FpVYM%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cricardo.jacomini%40jhu.edu%7C08d3e06858cd4c3029ff08d9bb1df0a7%7C9fa4f438b1e6473b803f86f8aedf0dec%7C0%7C0%7C637746559540321245%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=h9PVumdF82EphKPeQ6Z0UtU1gKVOqw2Pj19kQK2jWOg%3D&reserved=0> or Android<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cricardo.jacomini%40jhu.edu%7C08d3e06858cd4c3029ff08d9bb1df0a7%7C9fa4f438b1e6473b803f86f8aedf0dec%7C0%7C0%7C637746559540321245%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=I9NryZG4Hl71RAv7OuJko%2BbdK2F8QHZYXXjiuYkbiwc%3D&reserved=0>.

**Comment by marissaDubbelaar** [comment]
Hey Ricardo,

I am happy to hear that 😄  and don't worry about the PR, I also make enough mistakes too 😅 .
If it is also fine for you, then we can close this PR 😉 

Kind regards,

Marissa

**Comment by ricardojacomini** [comment]
Hi,

Yeah, please sure thing. You can close it.

I will send other. Lol.

Thanks

Ricardo S. Jacomini
sent from my mobile device
________________________________

**Pull request closed without merging**
