### PR TITLE
branch.yml

### PR DESCRIPTION
**Pull request by Leon-Bichmann**
Many thanks to contributing to nf-core/mhcquant!

Please fill in the appropriate checklist below (delete whatever is not relevant). These are the most common things requested on pull requests (PRs).

## PR checklist
 - [ ] This comment contains a description of changes (with reason)
 - [ ] If you've fixed a bug or added code that should be tested, add tests!
 - [ ] If necessary, also make a PR on the [nf-core/mhcquant branch on the nf-core/test-datasets repo]( https://github.com/nf-core/test-datasets/pull/new/nf-core/mhcquant)
 - [ ] Ensure the test suite passes (`nextflow run . -profile test,docker`).
 - [ ] Make sure your code lints (`nf-core lint .`).
 - [ ] Documentation in `docs` is updated
 - [ ] `CHANGELOG.md` is updated
 - [ ] `README.md` is updated

**Learn more about contributing:** https://github.com/nf-core/mhcquant/tree/master/.github/CONTRIBUTING.md

### CODE REVIEW

**Comment by Zethson** [comment]
```
found character '%' that cannot start any token
  in "/home/runner/work/mhcquant/mhcquant/.github/workflows/branch.yml", line 17, column 2
```

**Comment by Zethson** [comment]
Not sure why it doesn't like the percentage signs. I think that they're part of the GithubCI specifications. I would merge it anyways.

**Comment by Leon-Bichmann** [comment]
hmm.. yeah but it seems to break all the linting tests

**Comment by Zethson** [comment]
It's breaking the yaml linting.

But I think that the percentage stuff is part of Github CI

**Comment by drpatelh** [comment]
Nope the `raw`/`endraw` bits aren't! They are for the `cookiecutter` portion of `nf-core` `create`. If in doubt, create a new pipeline with the same manifest fields in `nextflow.config` from the `dev` version of `tools` and copy the file across. The branch tests will fail until we do a new release.

**Comment by Zethson** [comment]
Are you sure?
https://github.com/jwalton/jwalton.github.io/blob/master/_posts/2019-09-10-github-ci.markdown

This guy for example is also using the raw annotations.

**Comment by Zethson** [comment]
Ah, @drpatelh you are correct:

https://cookiecutter.readthedocs.io/en/1.7.0/troubleshooting.html#i-m-having-trouble-generating-jinja-templates-from-jinja-templates

All right then :)
Let's remove them.

**Comment by Leon-Bichmann** [comment]
so what exactly needs to be removed?

**Comment by drpatelh** [comment]
I would just revert this file back to the one you had with the failing branch tests because you don't have a badge for that. You so however now have failing lint tests because you updated the file and you do have a badge for that. You would remove the `{% raw %}` and `{% endraw %}` bits.

**Pull request closed without merging**
