### PR TITLE
Add social preview image

### PR DESCRIPTION
**Pull request by MaxUlysse**
- Add social preview image

## PR checklist
 - [ ] This comment contains a description of changes (with reason)
 - [ ] If you've fixed a bug or added code that should be tested, add tests!
 - [ ] If necessary, also make a PR on the [nf-core/mhcquant branch on the nf-core/test-datasets repo]( https://github.com/nf-core/test-datasets/pull/new/nf-core/mhcquant)
 - [ ] Ensure the test suite passes (`nextflow run . -profile test,docker`).
 - [ ] Make sure your code lints (`nf-core lint .`).
 - [ ] Documentation in `docs` is updated
 - [ ] `CHANGELOG.md` is updated
 - [ ] `README.md` is updated

**Learn more about contributing:** https://github.com/nf-core/mhcquant/tree/master/.github/CONTRIBUTING.md

### CODE REVIEW

**Comment by Leon-Bichmann** [comment]
should we just merge this one?

**Comment by Zethson** [comment]
Yes.
We trust our god @MaxUlysse

**Comment by Zethson** [comment]
We can add the pipeline preview image to the top of the README.

**Comment by Leon-Bichmann** [comment]
ok !

**Pull request merged**
